name: cat_monitoring_app
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  english_words: ^4.0.0
  flutter_lorem: ^2.0.0
  flutter:
    sdk: flutter
  camera:
  gap:
  external_path:
  media_scanner:

  cupertino_icons: ^1.0.6
  google_fonts:
  firebase_core: ^2.32.0
  cloud_firestore: ^4.14.0
  flutter_share: ^2.0.0
  path_provider: ^2.1.3
  gallery_saver: ^2.3.2
  image_picker: ^1.1.2
  flutter_blue: ^0.8.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.0
  firebase_auth: ^4.20.0
  firebase_storage: ^11.7.7
  path: ^1.9.0
  flutter_blue_plus: ^1.32.11
  firebase_database: ^10.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/


